### ISSUE TITLE
One image is missing

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#18]
Previous Behaviour

![image](https://user-images.githubusercontent.com/84350895/186074214-ff5b440b-1f85-4fab-81a4-453b04c2bbc7.png)

As you can see, one image is missing
Fix that

**Comment by aadil494** [comment]
@Kanika637 The problem is that the image url for that image doesn't for that image , The url is incorrect

image with correct url 
![image](https://user-images.githubusercontent.com/38073631/186077267-1c47c639-600f-4faf-a389-451e2366aef9.png)

image with incorrect url 
![image](https://user-images.githubusercontent.com/38073631/186077347-d964bb75-62b5-4196-8e12-49a9d694d95a.png)

**Comment by Kanika637** [comment]
Okay got it @aadil494 , Can you change this with any other product image as well as a different product name too?
If Yes, I can assign you this issue👍`

**Comment by developer-irfan** [comment]
hey @Kanika637 assign me i will fix it

**Comment by Kanika637** [comment]
Here you go @developer-irfan 👍

**Comment by aadil494** [comment]
@Kanika637  already added in #20

**Comment by Kanika637** [comment]
Got it @aadil494 ✌️
