### ISSUE TITLE
Improve the folder structure of the project

### ISSUE THREAD

**Issue by pratiksrivastava01** [Kanika637/amazon-clone#68]
Hey @Kanika637 I want to arrange the folder structure int the src file of the project

**Comment by Jai-Solania-29** [comment]
@pratiksrivastava01  Hey, can you please elaborate on what actually you want to achieve?

**Comment by ShubhamPatil0723** [comment]
@Jai-Solania-29 I also think we need to rearrange src folder because everything is just dumped inside the source folder and it will get hard to find files once this project becomes big enough
Something similar to this
![image](https://user-images.githubusercontent.com/92074003/193446994-a46ce62e-aa9f-4a82-9639-f39135951af5.png)

This is how I arrange my folders

**Comment by pratiksrivastava01** [comment]
![image](https://user-images.githubusercontent.com/92784294/193450596-ff42a248-8360-4b7a-abdc-0a08bb4e253d.png)

@Jai-Solania-29 This is how i use to arrange my files and folders so that they can be arranged which looks neat

**Comment by Kanika637** [comment]
Hey @pratiksrivastava01, Thanks for showing your interest but right now we don't feel the requirement of changing the folder structure.

**Comment by pratiksrivastava01** [comment]
Ok thank you
